services:
    diceway:
        build: .
        image: diceway-app
        container_name: diceway
        ports:
            - "8080:80"
        env_file:
            - .env
        restart: unless-stopped
